# Generated by Django 5.2.4 on 2025-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(help_text='O logotipo que aparecerá no cabeçalho.', upload_to='logos/')),
                ('telefone_televendas', models.CharField(blank=True, help_text='Ex: 0800 123 4567', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
