# Generated by Django 5.2.4 on 2025-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguracao',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Número para o botão flutuante. Formato: 5511987654321 (código do país + DDD + número)', max_length=20),
        ),
    ]
