# Generated by Django 5.2.4 on 2025-08-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_siteconfiguracao_whatsapp_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguracao',
            name='cor_primaria',
            field=models.CharField(default='#341a6b', help_text='Cor principal do site (ex: #341a6b). Usada no cabeçalho e na busca.', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='cor_secundaria',
            field=models.CharField(default='#fd4f4f', help_text='Cor de destaque do site (ex: #fd4f4f). Usada em botões.', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='texto_explore_destinos',
            field=models.CharField(default='Explore nossos destinos', help_text='O título da seção de destinos na página inicial.', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Número para o botão flutuante. Formato: 5511987654321', max_length=20),
        ),
    ]
