# Generated by Django 5.2.4 on 2025-08-04 15:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_siteconfiguracao_cor_primaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='cor_primaria',
            field=colorfield.fields.ColorField(default='#341a6b', help_text='Cor principal do site (ex: #341a6b). Usada no cabeçalho e na busca.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='cor_secundaria',
            field=colorfield.fields.ColorField(default='#fd4f4f', help_text='Cor de destaque do site (ex: #fd4f4f). Usada em botões.', image_field=None, max_length=25, samples=None),
        ),
    ]
