# Generated by Django 5.2.4 on 2025-08-04 15:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_alter_siteconfiguracao_cor_primaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguracao',
            name='cor_fundo_hero',
            field=colorfield.fields.ColorField(default='#fd7e14', help_text='Cor de fundo da seção de busca na página inicial (o laranja).', image_field=None, max_length=25, samples=None),
        ),
    ]
