# Generated by Django 5.2.4 on 2025-08-04 17:41

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_siteconfiguracao_cor_fundo_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguracao',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Uma breve descrição do site para os resultados do Google.', max_length=160, verbose_name='Descrição do Site (SEO)'),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='seo_title',
            field=models.CharField(blank=True, help_text='O título que aparece na aba do navegador e nos resultados do Google.', max_length=70, verbose_name='Título do Site (SEO)'),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='tracking_scripts_body',
            field=models.TextField(blank=True, help_text='Cole aqui os scripts (Google Tag Manager) que devem ir logo após a abertura da tag <body>.', verbose_name='Scripts no Corpo (<body>)'),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='tracking_scripts_head',
            field=models.TextField(blank=True, help_text='Cole aqui os scripts de rastreamento (Google Analytics, Pixel do Facebook) que devem ir na tag <head>.', verbose_name='Scripts no Cabeçalho (<head>)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='cor_fundo_hero',
            field=colorfield.fields.ColorField(default='#fd7e14', help_text='Cor de fundo da seção de busca (o laranja).', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='cor_primaria',
            field=colorfield.fields.ColorField(default='#341a6b', help_text='Cor principal do site (ex: #341a6b).', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='cor_secundaria',
            field=colorfield.fields.ColorField(default='#fd4f4f', help_text='Cor de destaque do site (ex: #fd4f4f).', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='logotipo',
            field=models.ImageField(help_text='O logotipo que aparecerá no cabeçalho e no painel de admin.', upload_to='logos/'),
        ),
    ]
