# Generated by Django 5.2.4 on 2025-08-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_siteconfiguracao_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguracao',
            name='link_facebook',
            field=models.URLField(blank=True, verbose_name='Link do Facebook'),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='link_instagram',
            field=models.URLField(blank=True, verbose_name='Link do Instagram'),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='link_twitter',
            field=models.URLField(blank=True, verbose_name='Link do Twitter / X'),
        ),
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='tracking_scripts_body',
            field=models.TextField(blank=True, help_text='Cole aqui os scripts (Google Tag Manager, etc.).', verbose_name='Scripts no Corpo (<body>)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguracao',
            name='tracking_scripts_head',
            field=models.TextField(blank=True, help_text='Cole aqui os scripts de rastreamento (Google Analytics, etc.).', verbose_name='Scripts no Cabeçalho (<head>)'),
        ),
    ]
