# Generated by Django 5.2.4 on 2025-08-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Versão do título para a URL. Ex: seguro-viagem', unique=True)),
                ('conteudo', models.TextField(help_text='Use HTML para formatar o texto, se desejar.')),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
