# Generated by Django 5.2.4 on 2025-08-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_endereco_usuario_telefone_alter_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua / Logradouro'),
        ),
    ]
