# Generated by Django 5.2.4 on 2025-08-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem_padrao', models.ImageField(blank=True, null=True, upload_to='destinos_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DATA_FIXA', 'Data Fixa'), ('DATA_FLEXIVEL', 'Data Flexível (a combinar)')], default='DATA_FIXA', help_text='Selecione se o pacote tem datas pré-definidas ou se as datas são flexíveis.', max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(max_length=255)),
                ('descricao_longa', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_ida', models.DateField(blank=True, help_text="Obrigatório se o tipo for 'Data Fixa'.", null=True)),
                ('data_volta', models.DateField(blank=True, help_text="Obrigatório se o tipo for 'Data Fixa'.", null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='pacotes_imgs/')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacotes.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='pacotes.pacote')),
            ],
        ),
    ]
