# Generated by Django 5.2.4 on 2025-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='cidade_origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='duracao_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='duracao_noites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='inclui_aereo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacote',
            name='inclui_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destino',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destino',
            name='imagem_padrao',
            field=models.ImageField(blank=True, null=True, upload_to='destinos/'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_ida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_volta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='pacotes/'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='tipo',
            field=models.CharField(choices=[('DATA_FIXA', 'Data Fixa'), ('FLEXIVEL', 'Flexível')], default='FLEXIVEL', max_length=20),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
