# Generated by Django 5.2.4 on 2025-08-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0002_pacote_avaliacao_pacote_cidade_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='inclui_transfer',
            field=models.BooleanField(default=False, verbose_name='Inclui Transfer'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='taxas_inclusas',
            field=models.BooleanField(default=False, verbose_name='Taxas e impostos inclusos'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='descricao',
            field=models.TextField(blank=True, help_text='Uma breve descrição sobre o destino.', null=True),
        ),
        migrations.AlterField(
            model_name='destino',
            name='imagem_padrao',
            field=models.ImageField(blank=True, null=True, upload_to='destinos_imgs/'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nota de 0.0 a 5.0', max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='cidade_origem',
            field=models.CharField(blank=True, help_text='Ex: São Paulo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_ida',
            field=models.DateField(blank=True, help_text="Opcional se o tipo for 'Data Flexível'.", null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_volta',
            field=models.DateField(blank=True, help_text="Opcional se o tipo for 'Data Flexível'.", null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='pacotes.destino'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='duracao_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='duracao_noites',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='pacotes_imgs/'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='inclui_aereo',
            field=models.BooleanField(default=False, verbose_name='Inclui Aéreo'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='inclui_hotel',
            field=models.BooleanField(default=False, verbose_name='Inclui Hotel'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='nome',
            field=models.CharField(help_text='Ex: Pacotes para Rio de Janeiro', max_length=200),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço base por pessoa.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='tipo',
            field=models.CharField(choices=[('DATA_FIXA', 'Data Fixa'), ('DATA_FLEXIVEL', 'Data Flexível (a combinar)')], default='DATA_FLEXIVEL', max_length=20),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='pacotes.pacote')),
            ],
        ),
    ]
