# Generated by Django 5.2.4 on 2025-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0002_pacote_imagem_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagem_padrao',
            field=models.ImageField(blank=True, null=True, upload_to='destinos_imgs/'),
        ),
    ]
