# Generated by Django 5.2.4 on 2025-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0003_destino_imagem_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='tipo',
            field=models.CharField(choices=[('DATA_FIXA', 'Data Fixa'), ('DATA_FLEXIVEL', 'Data Flexível (a combinar)')], default='DATA_FIXA', help_text='Selecione se o pacote tem datas pré-definidas ou se as datas são flexíveis.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_ida',
            field=models.DateField(blank=True, help_text="Obrigatório se o tipo for 'Data Fixa'.", null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_volta',
            field=models.DateField(blank=True, help_text="Obrigatório se o tipo for 'Data Fixa'.", null=True),
        ),
    ]
