# Generated by Django 5.2.4 on 2025-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0004_reserva_delete_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('HOSPEDAGEM', 'Hospedagem'), ('PASSAGEM', 'Passagem Aérea'), ('CRUZEIRO', 'Cruzeiro'), ('SEGURO', 'Seguro Viagem'), ('DISNEY', 'Disney'), ('VISTO', 'Visto Consular'), ('CAMBIO', 'Câmbio'), ('OFERTA', 'Oferta Especial')], max_length=20)),
                ('nome', models.CharField(help_text='Ex: Assist Card AC 35 ou Ingresso 2 Dias Básico', max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='servicos/')),
                ('preco_formatado', models.CharField(help_text='Ex: R$ 500 ou U$ 99 por dia', max_length=100)),
                ('link_externo', models.URLField(blank=True, help_text='Link para uma página de parceiro, se houver.', null=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviço Adicional',
                'verbose_name_plural': 'Serviços Adicionais',
            },
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_ida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_volta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
