# Generated by Django 5.2.4 on 2025-08-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0005_servico_alter_pacote_data_ida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='link_externo',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='preco_formatado',
        ),
        migrations.AddField(
            model_name='servico',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nota de 0.0 a 5.0', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='cidade_origem',
            field=models.CharField(blank=True, help_text='Ex: São Paulo (se aplicável)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao_longa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao_noites',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='inclui_aereo',
            field=models.BooleanField(default=False, verbose_name='Inclui Aéreo'),
        ),
        migrations.AddField(
            model_name='servico',
            name='inclui_hotel',
            field=models.BooleanField(default=False, verbose_name='Inclui Hotel'),
        ),
        migrations.AddField(
            model_name='servico',
            name='inclui_transfer',
            field=models.BooleanField(default=False, verbose_name='Inclui Transfer'),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço base', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='taxas_inclusas',
            field=models.BooleanField(default=False, verbose_name='Taxas e impostos inclusos'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_ida',
            field=models.DateField(blank=True, help_text="Opcional se o tipo for 'Data Flexível'.", null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_volta',
            field=models.DateField(blank=True, help_text="Opcional se o tipo for 'Data Flexível'.", null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('OFERTA', 'Oferta Especial'), ('HOSPEDAGEM', 'Hospedagem'), ('PASSAGEM', 'Passagem Aérea'), ('CRUZEIRO', 'Cruzeiro'), ('SEGURO', 'Seguro Viagem'), ('DISNEY', 'Disney'), ('VISTO', 'Visto Consular'), ('CAMBIO', 'Câmbio')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/', verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(help_text='Ex: Hotel Copacabana Palace ou Seguro Viagem AC 35', max_length=200),
        ),
    ]
